# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 979f417a8bc4b8b5abb67b8cfd46429152c90c440315b2af62df273acb6287178aff23d7748f24e9ce8d0d5499eee092b052ca8f15403879934f0727af7138d7

test:
  secret_key_base: 7fcee64ae88cf01f2c3bf6a81e20575821beaa7f8ea7f425b8c6652c6b722d5ff23a31654afe3f07313fe584a16213999df2c57ca4452c10f3629be1c3a0cd8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
